services:
  postgres:
    container_name: emo_meter_container
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: emo_meter
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
    ports:
    - 5435:5432
    volumes:
    - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data: